__pkgname__ = 'opentargets'
__author__ = 'OpenTargets Core Team <support@targetvalidation.org>'
__author_email__ = 'support@targetvalidation.org'
__license__ = 'Apache License, Version 2.0'
__homepage__ = 'https://github.com/opentargets/opentargets-py'
__version__ = '3.0.0'
__api_major_version__ = '3'
__description__ = 'Client for Open Targets REST API at targetvalidation.org'
